# Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx4096M
kotlin.incremental.native=false
# Gradle
org.gradle.jvmargs=-Xmx6144M -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:+ParallelRefProcEnabled
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
# Android & AGP Modern Defaults
android.useAndroidX=true
android.nonTransitiveRClass=true
android.enableAppCompileTimeRClass=true
android.r8.optimizedResourceShrinking=true
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
kotlin.mpp.enableCInteropCommonization=true
