[versions]
agp = "9.4.1"
android-compileSdk = "37"
android-minSdk = "28"
android-targetSdk = "37"
cryptoRand = "0.6.0"
datastore = "1.2.1"
media3 = "1.11.1"
mockk = "1.14.11"
splashApiVersion = "1.2.0"
androidx-activity = "1.13.0"
androidx-appcompat = "1.8.0"
androidx-core = "1.19.0"
composeMultiplatform = "1.12.0"
composeMultiplatform-material3 = "1.12.0-alpha03"
compose-multiplatform-adaptive = "1.3.0-rc01"
androidx-tooling-version = "1.12.1"
cmpNav3 = "1.2.0-beta01"
navigationevent-compose = "1.1.0"
androidx-lifecycle = "2.11.0"
androidx-navigation = "2.9.8"
credentials = "1.7.0-alpha03"
googleid = "1.2.1"
test-runner = "1.7.0"
test-core = "1.7.0"
androidx-espresso = "3.7.0"
androidx-testExt = "1.3.0"
junit = "4.13.2"
kermit = "2.2.0"
kotlin = "2.4.20"
buildkonfig = "0.22.0"
posthog-kmp = "0.5.1"
koin-plugin = "1.2.1"
koin = "4.2.2"
measure = "0.20.0"
supabase = "3.8.0"
room3 = "3.0.3"
sqlite = "2.7.1"
ksp = "2.3.11"
skie = "0.10.14"
okio = "3.18.2"
atomic-fu = "0.33.0"
kotlinxImmutable = "0.5.2"
kotlinxDatetime = "0.8.0"
kotlinxSerialization = "1.11.0"
kotlinx-coroutines = "1.11.0"
workRuntimeKtx = "2.11.2"
kotlinx-io = "0.9.1"
google-fonts = "1.12.1"
materialKolor = "5.0.1"
assertk = "0.28.1"
turbine = "1.2.1"

[libraries]
crypto-rand = { module = "org.kotlincrypto.random:crypto-rand", version.ref = "cryptoRand" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-testJunit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
junit = { module = "junit:junit", version.ref = "junit" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-testExt-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-testExt" }
androidx-rules = { module = "androidx.test:rules", version.ref = "test-runner" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-espresso" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
# Navigation & Lifecycle (CMP Multiplatform compatible)
androidx-lifecycle-viewmodelCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtimeCompose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "androidx-navigation" }
#nav
jetbrains-lifecycle-viewmodelNavigation3 = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-navigation3", version.ref = "androidx-lifecycle" }
jetbrains-material3-adaptiveNavigation3 = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation3", version.ref = "compose-multiplatform-adaptive" }
jetbrains-navigation3-ui = { module = "org.jetbrains.androidx.navigation3:navigation3-ui", version.ref = "cmpNav3" }
jetbrains-navevent-compose = { module = "org.jetbrains.androidx.navigationevent:navigationevent-compose", version.ref = "navigationevent-compose" }
#cmp
cmp-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
cmp-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
cmp-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
cmp-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "composeMultiplatform" }
cmp-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "composeMultiplatform" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-tooling-version" }
cmp-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "composeMultiplatform-material3" }
cmp-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
cmp-ui-test = { module = "org.jetbrains.compose.ui:ui-test", version.ref = "composeMultiplatform" }
cmp-ui-test-junit = { module = "org.jetbrains.compose.ui:ui-test-junit4", version.ref = "composeMultiplatform" }
cmp-adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "compose-multiplatform-adaptive" }
# Android Splash
androidx-splash = { module = "androidx.core:core-splashscreen", version.ref = "splashApiVersion" }
# Analytics
posthog-kmp = { group = "com.posthog", name = "posthog-kmp", version.ref = "posthog-kmp" }
# Koin
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-test = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koin-test-junit = { module = "io.insert-koin:koin-test-junit4", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-viewmodel = { module = "io.insert-koin:koin-core-viewmodel", version.ref = "koin" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-android-startup = { module = "io.insert-koin:koin-androidx-startup", version.ref = "koin" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
# Kermit
kermit = { module = "co.touchlab:kermit", version.ref = "kermit" }
kermit-koin = { module = "co.touchlab:kermit-koin", version.ref = "kermit" }
# Measure
measure-android = { module = "sh.measure:measure-android", version.ref = "measure" }
# Supabase
supabase-postgrest = { module = "io.github.jan-tennert.supabase:postgrest-kt", version.ref = "supabase" }
supabase-auth = { module = "io.github.jan-tennert.supabase:auth-kt", version.ref = "supabase" }
# AndroidX Test
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
androidx-core = { group = "androidx.test", name = "core", version.ref = "test-core" }
# Room DB
androidx-sqlite-framework = { module = "androidx.sqlite:sqlite-framework", version.ref = "sqlite" }
androidx-room3-runtime = { module = "androidx.room3:room3-runtime", version.ref = "room3" }
androidx-room3-compiler = { module = "androidx.room3:room3-compiler", version.ref = "room3" }
androidx-room3-sqlite-wrapper = { module = "androidx.room3:room3-sqlite-wrapper", version.ref = "room3" }
# Okio
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
kotlinx-io-core = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlinx-io" }
kotlinx-io-okio = { module = "org.jetbrains.kotlinx:kotlinx-io-okio", version.ref = "kotlinx-io" }
# Kotlinx
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinxSerialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }
# Credentials
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-play-services-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
# Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
# Work Manager
androidx-work-multiprocess = { module = "androidx.work:work-multiprocess", version.ref = "workRuntimeKtx" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
androidx-work-test = { module = "androidx.work:work-testing", version.ref = "workRuntimeKtx" }
#datastore
androidx-datastore = { module = "androidx.datastore:datastore-core", version.ref = "datastore" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences-core", version.ref = "datastore" }
androidx-datastore-okio = { module = "androidx.datastore:datastore-core-okio", version.ref = "datastore" }
# downloadable fonts
androidx-downloadable-fonts = { module = "androidx.compose.ui:ui-text-google-fonts", version.ref = "google-fonts" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
#exoplayer
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-exoplayer-dash = { module = "androidx.media3:media3-exoplayer-dash", version.ref = "media3" }
androidx-media3-testing = { module = "androidx.media3:media3-test-utils", version.ref = "media3" }
#assertk
asserrtk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
#mock
mockk-agent = { module = "io.mockk:mockk-agent", version.ref = "mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "mockk" }

[plugins]
#agp
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidLint = { id = "com.android.lint", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
#compose and kotlin
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose-multiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
#others
build-konfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }
koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koin-plugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
androidx-room3 = { id = "androidx.room3", version.ref = "room3" }
atomic-fu = { id = "org.jetbrains.kotlinx.atomicfu", version.ref = "atomic-fu" }
#skie
skie = { id = "co.touchlab.skie", version.ref = "skie" }

[bundles]
testing-android = ["androidx-testExt-junit", "androidx-espresso-core", "koin-test", "koin-test-junit", "kotlin-test", "kotlin-testJunit", "asserrtk"]
testing-common = ["koin-test", "kotlin-test"]
koin-common = ["koin-core", "koin-annotations"]
koin-compose = ["koin-viewmodel", "koin-compose", "koin-compose-viewmodel"]
kotlinx-common = ["kotlinx-coroutines-core", "kotlinx-datetime", "kotlinx-collections-immutable", "kotlinx-serialization-core", "kotlinx-io-core"]
koin-android = ["koin-android", "koin-android-startup"]
datastore = ["androidx-datastore", "androidx-datastore-preferences", "androidx-datastore-okio"]
compose-ui = ["cmp-runtime", "cmp-foundation", "cmp-ui", "cmp-material3", "cmp-components-resources", "cmp-adaptive", "cmp-ui-tooling-preview"]
androidx-lifecycle = ["androidx-lifecycle-viewmodelCompose", "androidx-lifecycle-runtimeCompose", ]
compose-navigation3 = ["jetbrains-lifecycle-viewmodelNavigation3", "jetbrains-material3-adaptiveNavigation3", "jetbrains-navigation3-ui", "jetbrains-navevent-compose"]
